name: JoinMessenger
version: '${project.version}'
main: siea.dev.joinmessenger.JoinMessenger
load: STARTUP
authors: [siea]
description: A Plugin to modify Join and Quit messages
website: siea.dev
api-version: 1.13
